
var __cov_EaRlxBaFpTRW2_e7D8l3TQ = (Function('return this'))();
if (!__cov_EaRlxBaFpTRW2_e7D8l3TQ.__coverage__) { __cov_EaRlxBaFpTRW2_e7D8l3TQ.__coverage__ = {}; }
__cov_EaRlxBaFpTRW2_e7D8l3TQ = __cov_EaRlxBaFpTRW2_e7D8l3TQ.__coverage__;
if (!(__cov_EaRlxBaFpTRW2_e7D8l3TQ['/home/adam/workspace/pokedex.org/src/js/client/orig/shared/worker.js'])) {
   __cov_EaRlxBaFpTRW2_e7D8l3TQ['/home/adam/workspace/pokedex.org/src/js/client/orig/shared/worker.js'] = {"path":"/home/adam/workspace/pokedex.org/src/js/client/orig/shared/worker.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0},"b":{"1":[0,0]},"f":{},"fnMap":{},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":44}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":39}},"3":{"start":{"line":4,"column":0},"end":{"line":4,"column":11}},"4":{"start":{"line":6,"column":0},"end":{"line":12,"column":1}},"5":{"start":{"line":7,"column":2},"end":{"line":7,"column":38}},"6":{"start":{"line":11,"column":2},"end":{"line":11,"column":44}},"7":{"start":{"line":14,"column":0},"end":{"line":16,"column":3}},"8":{"start":{"line":15,"column":2},"end":{"line":15,"column":49}},"9":{"start":{"line":20,"column":0},"end":{"line":23,"column":3}},"10":{"start":{"line":25,"column":0},"end":{"line":25,"column":24}}},"branchMap":{"1":{"line":6,"type":"if","locations":[{"start":{"line":6,"column":0},"end":{"line":6,"column":0}},{"start":{"line":6,"column":0},"end":{"line":6,"column":0}}]}}};
}
__cov_EaRlxBaFpTRW2_e7D8l3TQ = __cov_EaRlxBaFpTRW2_e7D8l3TQ['/home/adam/workspace/pokedex.org/src/js/client/orig/shared/worker.js'];
__cov_EaRlxBaFpTRW2_e7D8l3TQ.s['1']++;var PseudoWorker=require('pseudo-worker');__cov_EaRlxBaFpTRW2_e7D8l3TQ.s['2']++;var utils=require('./../main/utils');__cov_EaRlxBaFpTRW2_e7D8l3TQ.s['3']++;var worker;__cov_EaRlxBaFpTRW2_e7D8l3TQ.s['4']++;if(utils.hasWebWorkerIDB()){__cov_EaRlxBaFpTRW2_e7D8l3TQ.b['1'][0]++;__cov_EaRlxBaFpTRW2_e7D8l3TQ.s['5']++;worker=new Worker('js/worker.js');}else{__cov_EaRlxBaFpTRW2_e7D8l3TQ.b['1'][1]++;__cov_EaRlxBaFpTRW2_e7D8l3TQ.s['6']++;worker=new PseudoWorker('js/worker.js');}__cov_EaRlxBaFpTRW2_e7D8l3TQ.s['7']++;worker.addEventListener('error',e=>{__cov_EaRlxBaFpTRW2_e7D8l3TQ.s['8']++;console.warn('worker threw an error',e.error);});__cov_EaRlxBaFpTRW2_e7D8l3TQ.s['9']++;worker.postMessage({origin:window.location.origin,type:'origin'});__cov_EaRlxBaFpTRW2_e7D8l3TQ.s['10']++;module.exports=worker;
