
var __cov_c1CUmXns25bIScTnhQHPbw = (Function('return this'))();
if (!__cov_c1CUmXns25bIScTnhQHPbw.__coverage__) { __cov_c1CUmXns25bIScTnhQHPbw.__coverage__ = {}; }
__cov_c1CUmXns25bIScTnhQHPbw = __cov_c1CUmXns25bIScTnhQHPbw.__coverage__;
if (!(__cov_c1CUmXns25bIScTnhQHPbw['/home/adam/workspace/pokedex.org/src/js/client/orig/main/progress.js'])) {
   __cov_c1CUmXns25bIScTnhQHPbw['/home/adam/workspace/pokedex.org/src/js/client/orig/main/progress.js'] = {"path":"/home/adam/workspace/pokedex.org/src/js/client/orig/main/progress.js","s":{"1":0,"2":0,"3":1,"4":0,"5":1,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0},"b":{"1":[0,0]},"f":{"1":0,"2":0,"3":0,"4":0},"fnMap":{"1":{"name":"init","line":5,"loc":{"start":{"line":5,"column":0},"end":{"line":5,"column":16}}},"2":{"name":"Progress","line":9,"loc":{"start":{"line":9,"column":0},"end":{"line":9,"column":20}}},"3":{"name":"(anonymous_3)","line":12,"loc":{"start":{"line":12,"column":27},"end":{"line":12,"column":39}}},"4":{"name":"(anonymous_4)","line":17,"loc":{"start":{"line":17,"column":25},"end":{"line":17,"column":37}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":32}},"2":{"start":{"line":3,"column":0},"end":{"line":3,"column":9}},"3":{"start":{"line":5,"column":0},"end":{"line":7,"column":1}},"4":{"start":{"line":6,"column":2},"end":{"line":6,"column":37}},"5":{"start":{"line":9,"column":0},"end":{"line":10,"column":1}},"6":{"start":{"line":12,"column":0},"end":{"line":15,"column":2}},"7":{"start":{"line":13,"column":2},"end":{"line":13,"column":9}},"8":{"start":{"line":14,"column":2},"end":{"line":14,"column":30}},"9":{"start":{"line":17,"column":0},"end":{"line":20,"column":2}},"10":{"start":{"line":18,"column":2},"end":{"line":18,"column":9}},"11":{"start":{"line":19,"column":2},"end":{"line":19,"column":33}},"12":{"start":{"line":22,"column":0},"end":{"line":22,"column":32}}},"branchMap":{"1":{"line":6,"type":"binary-expr","locations":[{"start":{"line":6,"column":9},"end":{"line":6,"column":13}},{"start":{"line":6,"column":17},"end":{"line":6,"column":36}}]}}};
}
__cov_c1CUmXns25bIScTnhQHPbw = __cov_c1CUmXns25bIScTnhQHPbw['/home/adam/workspace/pokedex.org/src/js/client/orig/main/progress.js'];
__cov_c1CUmXns25bIScTnhQHPbw.s['1']++;var $=require('./jqueryLite');__cov_c1CUmXns25bIScTnhQHPbw.s['2']++;var mask;function init(){__cov_c1CUmXns25bIScTnhQHPbw.f['1']++;__cov_c1CUmXns25bIScTnhQHPbw.s['4']++;mask=(__cov_c1CUmXns25bIScTnhQHPbw.b['1'][0]++,mask)||(__cov_c1CUmXns25bIScTnhQHPbw.b['1'][1]++,$('#progress-mask'));}function Progress(){__cov_c1CUmXns25bIScTnhQHPbw.f['2']++;}__cov_c1CUmXns25bIScTnhQHPbw.s['6']++;Progress.prototype.start=function(){__cov_c1CUmXns25bIScTnhQHPbw.f['3']++;__cov_c1CUmXns25bIScTnhQHPbw.s['7']++;init();__cov_c1CUmXns25bIScTnhQHPbw.s['8']++;mask.classList.add('shown');};__cov_c1CUmXns25bIScTnhQHPbw.s['9']++;Progress.prototype.end=function(){__cov_c1CUmXns25bIScTnhQHPbw.f['4']++;__cov_c1CUmXns25bIScTnhQHPbw.s['10']++;init();__cov_c1CUmXns25bIScTnhQHPbw.s['11']++;mask.classList.remove('shown');};__cov_c1CUmXns25bIScTnhQHPbw.s['12']++;module.exports=new Progress();
