
var __cov_hrgSWTRcTSMqeKtsrgKBsQ = (Function('return this'))();
if (!__cov_hrgSWTRcTSMqeKtsrgKBsQ.__coverage__) { __cov_hrgSWTRcTSMqeKtsrgKBsQ.__coverage__ = {}; }
__cov_hrgSWTRcTSMqeKtsrgKBsQ = __cov_hrgSWTRcTSMqeKtsrgKBsQ.__coverage__;
if (!(__cov_hrgSWTRcTSMqeKtsrgKBsQ['/home/adam/workspace/pokedex.org/src/js/client/orig/main/rippleEffect.js'])) {
   __cov_hrgSWTRcTSMqeKtsrgKBsQ['/home/adam/workspace/pokedex.org/src/js/client/orig/main/rippleEffect.js'] = {"path":"/home/adam/workspace/pokedex.org/src/js/client/orig/main/rippleEffect.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":0,"17":0,"18":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"eventHandler","line":7,"loc":{"start":{"line":7,"column":17},"end":{"line":7,"column":71}}},"2":{"name":"(anonymous_2)","line":34,"loc":{"start":{"line":34,"column":20},"end":{"line":34,"column":31}}}},"statementMap":{"1":{"start":{"line":5,"column":0},"end":{"line":5,"column":38}},"2":{"start":{"line":7,"column":0},"end":{"line":37,"column":2}},"3":{"start":{"line":9,"column":2},"end":{"line":11,"column":3}},"4":{"start":{"line":10,"column":4},"end":{"line":10,"column":11}},"5":{"start":{"line":14,"column":2},"end":{"line":16,"column":3}},"6":{"start":{"line":15,"column":4},"end":{"line":15,"column":11}},"7":{"start":{"line":18,"column":2},"end":{"line":18,"column":47}},"8":{"start":{"line":19,"column":2},"end":{"line":19,"column":35}},"9":{"start":{"line":22,"column":2},"end":{"line":22,"column":46}},"10":{"start":{"line":23,"column":2},"end":{"line":23,"column":29}},"11":{"start":{"line":25,"column":2},"end":{"line":25,"column":28}},"12":{"start":{"line":27,"column":2},"end":{"line":27,"column":42}},"13":{"start":{"line":28,"column":2},"end":{"line":28,"column":41}},"14":{"start":{"line":29,"column":2},"end":{"line":29,"column":49}},"15":{"start":{"line":30,"column":2},"end":{"line":30,"column":50}},"16":{"start":{"line":32,"column":2},"end":{"line":32,"column":33}},"17":{"start":{"line":34,"column":2},"end":{"line":36,"column":11}},"18":{"start":{"line":35,"column":4},"end":{"line":35,"column":35}}},"branchMap":{"1":{"line":9,"type":"if","locations":[{"start":{"line":9,"column":2},"end":{"line":9,"column":2}},{"start":{"line":9,"column":2},"end":{"line":9,"column":2}}]},"2":{"line":14,"type":"if","locations":[{"start":{"line":14,"column":2},"end":{"line":14,"column":2}},{"start":{"line":14,"column":2},"end":{"line":14,"column":2}}]}}};
}
__cov_hrgSWTRcTSMqeKtsrgKBsQ = __cov_hrgSWTRcTSMqeKtsrgKBsQ['/home/adam/workspace/pokedex.org/src/js/client/orig/main/rippleEffect.js'];
__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['1']++;var rippleClass='mui-ripple-effect';__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['2']++;module.exports=function eventHandler(ev,buttonEl,xOffset,yOffset){__cov_hrgSWTRcTSMqeKtsrgKBsQ.f['1']++;__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['3']++;if(ev.button!==0){__cov_hrgSWTRcTSMqeKtsrgKBsQ.b['1'][0]++;__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['4']++;return;}else{__cov_hrgSWTRcTSMqeKtsrgKBsQ.b['1'][1]++;}__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['5']++;if(buttonEl.disabled===true){__cov_hrgSWTRcTSMqeKtsrgKBsQ.b['2'][0]++;__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['6']++;return;}else{__cov_hrgSWTRcTSMqeKtsrgKBsQ.b['2'][1]++;}__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['7']++;var rippleEl=document.createElement('div');__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['8']++;rippleEl.className=rippleClass;__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['9']++;var rect=buttonEl.getBoundingClientRect();__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['10']++;var diameter=rect.height;__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['11']++;var radius=diameter/2;__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['12']++;rippleEl.style.height=diameter+'px';__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['13']++;rippleEl.style.width=diameter+'px';__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['14']++;rippleEl.style.top=yOffset-radius+'px';__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['15']++;rippleEl.style.left=xOffset-radius+'px';__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['16']++;buttonEl.appendChild(rippleEl);__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['17']++;window.setTimeout(function(){__cov_hrgSWTRcTSMqeKtsrgKBsQ.f['2']++;__cov_hrgSWTRcTSMqeKtsrgKBsQ.s['18']++;buttonEl.removeChild(rippleEl);},2000);};
