
var __cov_RY$zdL14TbHvmcYmmbRWEA = (Function('return this'))();
if (!__cov_RY$zdL14TbHvmcYmmbRWEA.__coverage__) { __cov_RY$zdL14TbHvmcYmmbRWEA.__coverage__ = {}; }
__cov_RY$zdL14TbHvmcYmmbRWEA = __cov_RY$zdL14TbHvmcYmmbRWEA.__coverage__;
if (!(__cov_RY$zdL14TbHvmcYmmbRWEA['/home/adam/workspace/pokedex.org/src/js/client/orig/main/router.js'])) {
   __cov_RY$zdL14TbHvmcYmmbRWEA['/home/adam/workspace/pokedex.org/src/js/client/orig/main/router.js'] = {"path":"/home/adam/workspace/pokedex.org/src/js/client/orig/main/router.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":1,"16":0,"17":1,"18":0,"19":0,"20":0,"21":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"toMonsterDetail","line":24,"loc":{"start":{"line":24,"column":0},"end":{"line":24,"column":37}}},"2":{"name":"toMainView","line":28,"loc":{"start":{"line":28,"column":0},"end":{"line":28,"column":22}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":31}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":36}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":41}},"4":{"start":{"line":4,"column":0},"end":{"line":4,"column":65}},"5":{"start":{"line":6,"column":0},"end":{"line":6,"column":19}},"6":{"start":{"line":7,"column":0},"end":{"line":7,"column":21}},"7":{"start":{"line":9,"column":0},"end":{"line":22,"column":13}},"8":{"start":{"line":10,"column":2},"end":{"line":10,"column":51}},"9":{"start":{"line":11,"column":2},"end":{"line":14,"column":5}},"10":{"start":{"line":15,"column":2},"end":{"line":15,"column":54}},"11":{"start":{"line":16,"column":2},"end":{"line":16,"column":30}},"12":{"start":{"line":18,"column":2},"end":{"line":18,"column":26}},"13":{"start":{"line":19,"column":2},"end":{"line":21,"column":3}},"14":{"start":{"line":20,"column":4},"end":{"line":20,"column":54}},"15":{"start":{"line":24,"column":0},"end":{"line":26,"column":1}},"16":{"start":{"line":25,"column":2},"end":{"line":25,"column":44}},"17":{"start":{"line":28,"column":0},"end":{"line":34,"column":1}},"18":{"start":{"line":29,"column":2},"end":{"line":33,"column":3}},"19":{"start":{"line":30,"column":4},"end":{"line":30,"column":19}},"20":{"start":{"line":32,"column":4},"end":{"line":32,"column":25}},"21":{"start":{"line":36,"column":0},"end":{"line":39,"column":2}}},"branchMap":{"1":{"line":19,"type":"if","locations":[{"start":{"line":19,"column":2},"end":{"line":19,"column":2}},{"start":{"line":19,"column":2},"end":{"line":19,"column":2}}]},"2":{"line":29,"type":"if","locations":[{"start":{"line":29,"column":2},"end":{"line":29,"column":2}},{"start":{"line":29,"column":2},"end":{"line":29,"column":2}}]}}};
}
__cov_RY$zdL14TbHvmcYmmbRWEA = __cov_RY$zdL14TbHvmcYmmbRWEA['/home/adam/workspace/pokedex.org/src/js/client/orig/main/router.js'];
__cov_RY$zdL14TbHvmcYmmbRWEA.s['1']++;var Navigo=require('navigo');__cov_RY$zdL14TbHvmcYmmbRWEA.s['2']++;var router=new Navigo(null,true);__cov_RY$zdL14TbHvmcYmmbRWEA.s['3']++;var worker=require('../shared/worker');__cov_RY$zdL14TbHvmcYmmbRWEA.s['4']++;var detailViewOrchestrator=require('./detailViewOrchestrator');__cov_RY$zdL14TbHvmcYmmbRWEA.s['5']++;var lastNationalId;__cov_RY$zdL14TbHvmcYmmbRWEA.s['6']++;var landedOnMainView;__cov_RY$zdL14TbHvmcYmmbRWEA.s['7']++;router.on('/pokemon/:nationalId',params=>{__cov_RY$zdL14TbHvmcYmmbRWEA.s['8']++;var nationalId=parseInt(params.nationalId,10);__cov_RY$zdL14TbHvmcYmmbRWEA.s['9']++;worker.postMessage({type:'detail',nationalId:nationalId});__cov_RY$zdL14TbHvmcYmmbRWEA.s['10']++;detailViewOrchestrator.animateInPartOne(nationalId);__cov_RY$zdL14TbHvmcYmmbRWEA.s['11']++;lastNationalId=nationalId;}).on('/',()=>{__cov_RY$zdL14TbHvmcYmmbRWEA.s['12']++;landedOnMainView=true;__cov_RY$zdL14TbHvmcYmmbRWEA.s['13']++;if(typeof lastNationalId==='number'){__cov_RY$zdL14TbHvmcYmmbRWEA.b['1'][0]++;__cov_RY$zdL14TbHvmcYmmbRWEA.s['14']++;detailViewOrchestrator.animateOut(lastNationalId);}else{__cov_RY$zdL14TbHvmcYmmbRWEA.b['1'][1]++;}}).resolve();function toMonsterDetail(nationalId){__cov_RY$zdL14TbHvmcYmmbRWEA.f['1']++;__cov_RY$zdL14TbHvmcYmmbRWEA.s['16']++;router.navigate('/pokemon/'+nationalId);}function toMainView(){__cov_RY$zdL14TbHvmcYmmbRWEA.f['2']++;__cov_RY$zdL14TbHvmcYmmbRWEA.s['18']++;if(landedOnMainView){__cov_RY$zdL14TbHvmcYmmbRWEA.b['2'][0]++;__cov_RY$zdL14TbHvmcYmmbRWEA.s['19']++;history.back();}else{__cov_RY$zdL14TbHvmcYmmbRWEA.b['2'][1]++;__cov_RY$zdL14TbHvmcYmmbRWEA.s['20']++;router.navigate('/');}}__cov_RY$zdL14TbHvmcYmmbRWEA.s['21']++;module.exports={toMonsterDetail,toMainView};
