
var __cov_bvpsZ1hkkNPSlZLpt$wvdA = (Function('return this'))();
if (!__cov_bvpsZ1hkkNPSlZLpt$wvdA.__coverage__) { __cov_bvpsZ1hkkNPSlZLpt$wvdA.__coverage__ = {}; }
__cov_bvpsZ1hkkNPSlZLpt$wvdA = __cov_bvpsZ1hkkNPSlZLpt$wvdA.__coverage__;
if (!(__cov_bvpsZ1hkkNPSlZLpt$wvdA['/home/adam/workspace/pokedex.org/src/js/client/orig/main/searchBar.js'])) {
   __cov_bvpsZ1hkkNPSlZLpt$wvdA['/home/adam/workspace/pokedex.org/src/js/client/orig/main/searchBar.js'] = {"path":"/home/adam/workspace/pokedex.org/src/js/client/orig/main/searchBar.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0},"b":{},"f":{},"fnMap":{},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":43}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":35}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":37}},"4":{"start":{"line":4,"column":0},"end":{"line":4,"column":32}},"5":{"start":{"line":6,"column":0},"end":{"line":24,"column":3}},"6":{"start":{"line":8,"column":2},"end":{"line":8,"column":44}},"7":{"start":{"line":10,"column":2},"end":{"line":12,"column":5}},"8":{"start":{"line":11,"column":4},"end":{"line":11,"column":21}},"9":{"start":{"line":13,"column":2},"end":{"line":22,"column":10}},"10":{"start":{"line":14,"column":4},"end":{"line":14,"column":32}},"11":{"start":{"line":16,"column":4},"end":{"line":16,"column":53}},"12":{"start":{"line":17,"column":4},"end":{"line":17,"column":27}},"13":{"start":{"line":18,"column":4},"end":{"line":21,"column":7}}},"branchMap":{}};
}
__cov_bvpsZ1hkkNPSlZLpt$wvdA = __cov_bvpsZ1hkkNPSlZLpt$wvdA['/home/adam/workspace/pokedex.org/src/js/client/orig/main/searchBar.js'];
__cov_bvpsZ1hkkNPSlZLpt$wvdA.s['1']++;var worker=require('./../shared/worker');__cov_bvpsZ1hkkNPSlZLpt$wvdA.s['2']++;var debounce=require('debounce');__cov_bvpsZ1hkkNPSlZLpt$wvdA.s['3']++;var progress=require('./progress');__cov_bvpsZ1hkkNPSlZLpt$wvdA.s['4']++;var $=require('./jqueryLite');__cov_bvpsZ1hkkNPSlZLpt$wvdA.s['5']++;document.addEventListener('DOMContentLoaded',()=>{__cov_bvpsZ1hkkNPSlZLpt$wvdA.s['6']++;var searchBar=$('#monsters-search-bar');__cov_bvpsZ1hkkNPSlZLpt$wvdA.s['7']++;searchBar.addEventListener('input',()=>{__cov_bvpsZ1hkkNPSlZLpt$wvdA.s['8']++;progress.start();});__cov_bvpsZ1hkkNPSlZLpt$wvdA.s['9']++;searchBar.addEventListener('input',debounce(e=>{__cov_bvpsZ1hkkNPSlZLpt$wvdA.s['10']++;var filter=e.target.value;__cov_bvpsZ1hkkNPSlZLpt$wvdA.s['11']++;console.log('posting message to filter',filter);__cov_bvpsZ1hkkNPSlZLpt$wvdA.s['12']++;console.time('worker');__cov_bvpsZ1hkkNPSlZLpt$wvdA.s['13']++;worker.postMessage({filter:filter,type:'filter'});},50));});
