
var __cov_A8oDS5$aVG1qxFFRTtSdcA = (Function('return this'))();
if (!__cov_A8oDS5$aVG1qxFFRTtSdcA.__coverage__) { __cov_A8oDS5$aVG1qxFFRTtSdcA.__coverage__ = {}; }
__cov_A8oDS5$aVG1qxFFRTtSdcA = __cov_A8oDS5$aVG1qxFFRTtSdcA.__coverage__;
if (!(__cov_A8oDS5$aVG1qxFFRTtSdcA['/home/adam/workspace/pokedex.org/src/js/client/orig/main/themeManager.js'])) {
   __cov_A8oDS5$aVG1qxFFRTtSdcA['/home/adam/workspace/pokedex.org/src/js/client/orig/main/themeManager.js'] = {"path":"/home/adam/workspace/pokedex.org/src/js/client/orig/main/themeManager.js","s":{"1":0,"2":0,"3":0,"4":0,"5":1,"6":0,"7":0,"8":1,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"setThemeColor","line":7,"loc":{"start":{"line":7,"column":0},"end":{"line":7,"column":30}}},"2":{"name":"resetThemeColor","line":13,"loc":{"start":{"line":13,"column":0},"end":{"line":13,"column":27}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":32}},"2":{"start":{"line":3,"column":0},"end":{"line":3,"column":14}},"3":{"start":{"line":4,"column":0},"end":{"line":4,"column":13}},"4":{"start":{"line":5,"column":0},"end":{"line":5,"column":17}},"5":{"start":{"line":7,"column":0},"end":{"line":11,"column":1}},"6":{"start":{"line":8,"column":2},"end":{"line":8,"column":28}},"7":{"start":{"line":10,"column":2},"end":{"line":10,"column":45}},"8":{"start":{"line":13,"column":0},"end":{"line":16,"column":1}},"9":{"start":{"line":14,"column":2},"end":{"line":14,"column":31}},"10":{"start":{"line":15,"column":2},"end":{"line":15,"column":48}},"11":{"start":{"line":18,"column":0},"end":{"line":22,"column":3}},"12":{"start":{"line":19,"column":2},"end":{"line":19,"column":70}},"13":{"start":{"line":20,"column":2},"end":{"line":20,"column":31}},"14":{"start":{"line":21,"column":2},"end":{"line":21,"column":34}},"15":{"start":{"line":24,"column":0},"end":{"line":27,"column":2}}},"branchMap":{}};
}
__cov_A8oDS5$aVG1qxFFRTtSdcA = __cov_A8oDS5$aVG1qxFFRTtSdcA['/home/adam/workspace/pokedex.org/src/js/client/orig/main/themeManager.js'];
__cov_A8oDS5$aVG1qxFFRTtSdcA.s['1']++;var $=require('./jqueryLite');__cov_A8oDS5$aVG1qxFFRTtSdcA.s['2']++;var themeMeta;__cov_A8oDS5$aVG1qxFFRTtSdcA.s['3']++;var appTheme;__cov_A8oDS5$aVG1qxFFRTtSdcA.s['4']++;var headerAppBar;function setThemeColor(color){__cov_A8oDS5$aVG1qxFFRTtSdcA.f['1']++;__cov_A8oDS5$aVG1qxFFRTtSdcA.s['6']++;themeMeta.content=color;__cov_A8oDS5$aVG1qxFFRTtSdcA.s['7']++;headerAppBar.style.backgroundColor=color;}function resetThemeColor(){__cov_A8oDS5$aVG1qxFFRTtSdcA.f['2']++;__cov_A8oDS5$aVG1qxFFRTtSdcA.s['9']++;themeMeta.content=appTheme;__cov_A8oDS5$aVG1qxFFRTtSdcA.s['10']++;headerAppBar.style.backgroundColor=appTheme;}__cov_A8oDS5$aVG1qxFFRTtSdcA.s['11']++;document.addEventListener('DOMContentLoaded',()=>{__cov_A8oDS5$aVG1qxFFRTtSdcA.s['12']++;themeMeta=document.head.querySelector('meta[name="theme-color"]');__cov_A8oDS5$aVG1qxFFRTtSdcA.s['13']++;appTheme=themeMeta.content;__cov_A8oDS5$aVG1qxFFRTtSdcA.s['14']++;headerAppBar=$('.mui-appbar');});__cov_A8oDS5$aVG1qxFFRTtSdcA.s['15']++;module.exports={setThemeColor,resetThemeColor};
