
var __cov_laXYKFjO_E7OOzwCEsFKJA = (Function('return this'))();
if (!__cov_laXYKFjO_E7OOzwCEsFKJA.__coverage__) { __cov_laXYKFjO_E7OOzwCEsFKJA.__coverage__ = {}; }
__cov_laXYKFjO_E7OOzwCEsFKJA = __cov_laXYKFjO_E7OOzwCEsFKJA.__coverage__;
if (!(__cov_laXYKFjO_E7OOzwCEsFKJA['/home/adam/workspace/pokedex.org/src/js/client/orig/main/utils.js'])) {
   __cov_laXYKFjO_E7OOzwCEsFKJA['/home/adam/workspace/pokedex.org/src/js/client/orig/main/utils.js'] = {"path":"/home/adam/workspace/pokedex.org/src/js/client/orig/main/utils.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0},"b":{"1":[0,0,0,0],"2":[0,0],"3":[0,0,0]},"f":{},"fnMap":{},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":31,"column":2}},"2":{"start":{"line":5,"column":4},"end":{"line":8,"column":45}},"3":{"start":{"line":9,"column":4},"end":{"line":9,"column":21}},"4":{"start":{"line":13,"column":4},"end":{"line":13,"column":67}},"5":{"start":{"line":14,"column":4},"end":{"line":16,"column":5}},"6":{"start":{"line":15,"column":6},"end":{"line":15,"column":29}},"7":{"start":{"line":21,"column":4},"end":{"line":21,"column":62}},"8":{"start":{"line":24,"column":4},"end":{"line":24,"column":57}},"9":{"start":{"line":27,"column":4},"end":{"line":27,"column":63}},"10":{"start":{"line":29,"column":4},"end":{"line":29,"column":52}}},"branchMap":{"1":{"line":5,"type":"binary-expr","locations":[{"start":{"line":5,"column":19},"end":{"line":5,"column":54}},{"start":{"line":6,"column":6},"end":{"line":6,"column":59}},{"start":{"line":7,"column":6},"end":{"line":7,"column":41}},{"start":{"line":8,"column":6},"end":{"line":8,"column":44}}]},"2":{"line":14,"type":"if","locations":[{"start":{"line":14,"column":4},"end":{"line":14,"column":4}},{"start":{"line":14,"column":4},"end":{"line":14,"column":4}}]},"3":{"line":29,"type":"binary-expr","locations":[{"start":{"line":29,"column":11},"end":{"line":29,"column":22}},{"start":{"line":29,"column":26},"end":{"line":29,"column":36}},{"start":{"line":29,"column":40},"end":{"line":29,"column":51}}]}}};
}
__cov_laXYKFjO_E7OOzwCEsFKJA = __cov_laXYKFjO_E7OOzwCEsFKJA['/home/adam/workspace/pokedex.org/src/js/client/orig/main/utils.js'];
__cov_laXYKFjO_E7OOzwCEsFKJA.s['1']++;module.exports={hasWebWorkerIDB:()=>{__cov_laXYKFjO_E7OOzwCEsFKJA.s['2']++;var isSafari=(__cov_laXYKFjO_E7OOzwCEsFKJA.b['1'][0]++,typeof openDatabase!=='undefined')&&(__cov_laXYKFjO_E7OOzwCEsFKJA.b['1'][1]++,/(Safari|iPhone|iPad|iPod)/.test(navigator.userAgent))&&(__cov_laXYKFjO_E7OOzwCEsFKJA.b['1'][2]++,!/Chrome/.test(navigator.userAgent))&&(__cov_laXYKFjO_E7OOzwCEsFKJA.b['1'][3]++,!/BlackBerry/.test(navigator.platform));__cov_laXYKFjO_E7OOzwCEsFKJA.s['3']++;return!isSafari;},canRunHighPerfAnims:()=>{__cov_laXYKFjO_E7OOzwCEsFKJA.s['4']++;var force=window.location.search.match(/highPerfAnims=(\d)/);__cov_laXYKFjO_E7OOzwCEsFKJA.s['5']++;if(force){__cov_laXYKFjO_E7OOzwCEsFKJA.b['2'][0]++;__cov_laXYKFjO_E7OOzwCEsFKJA.s['6']++;return force[1]==1;}else{__cov_laXYKFjO_E7OOzwCEsFKJA.b['2'][1]++;}__cov_laXYKFjO_E7OOzwCEsFKJA.s['7']++;var isAndroid4=navigator.userAgent.match(/Android 4\./);__cov_laXYKFjO_E7OOzwCEsFKJA.s['8']++;var isFirefox=navigator.userAgent.match(/Firefox/);__cov_laXYKFjO_E7OOzwCEsFKJA.s['9']++;var isEdgeOrIE=navigator.userAgent.match(/(?:MSIE|Edge)/);__cov_laXYKFjO_E7OOzwCEsFKJA.s['10']++;return(__cov_laXYKFjO_E7OOzwCEsFKJA.b['3'][0]++,!isAndroid4)&&(__cov_laXYKFjO_E7OOzwCEsFKJA.b['3'][1]++,!isFirefox)&&(__cov_laXYKFjO_E7OOzwCEsFKJA.b['3'][2]++,!isEdgeOrIE);}};
